version: "3"

services:
  db:
    image: postgres:15.4
    container_name: hotelsoft-db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  app:
    container_name: hotelsoft-app
    restart: always
    build: .
    command: sh -c "npx prisma generate && npm run migrate && npm run start:dev"
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./prisma:/app/prisma
    depends_on:
      - db

volumes:
  pgdata:
