version: "3"

services:
  db:
    image: postgres:15.4
    container_name: hotelsoft-db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - hotelsoftData:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  app:
    container_name: hotelsoft-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    #    command: sh -c "npx prisma generate && npm run migrate && npm run start:dev"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    depends_on:
      - db

    environment:
      STATE: ${STATE}
      APP_HOST: ${APP_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_PORT: ${POSTGRES_PORT}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}

volumes:
  hotelsoftData:
