version: "3"

services:
  app:
    container_name: hotelsoft-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: cyngames/hotelsoft
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules

    environment:
      STATE: ${STATE}
      APP_HOST: ${APP_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PRISMA_BINARY_TARGETS: ${PRISMA_BINARY_TARGETS}
      PORT: ${PORT}
