version: '3.8'

services:
  app:
    container_name: hotelsoft-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: cyngames/hotelsoft
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    env_file:
      - .env.prod

  db:
    image: postgres:15.4
    container_name: hotelsoft-db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env.prod
