version: '3.8'

services:
  db:
    image: postgres:15.4
    container_name: hotelsoft-test-db
    restart: always
    ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
